### ISSUE TITLE
Loader should return a self reference of how re call itself.

### ISSUE THREAD

**Issue by guitavano** [deco-cx/apps#347]
https://discord.com/channels/985687648595243068/1199070604532396202/1199070604532396202

**Comment by lucis** [comment]
Problem: 

**Client-side pagination**
Sites want to load data on the server for the first run but allow users to eventually filter or paginate it on the client-side (without a full page reload). In order to keep results consistent, the code needs to "know" which loader to _invoke_. Now, the only solution is to call the selected loader directly in the code

**Comment by guitavano** [comment]
Solved by Partials and HTMX.
